=== aidansanchez07-prog/DAW/1-DAW/Lenguajes-de-Marcas/XML/Portal-meteorologico/clima.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="reporte_meteorologico">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="fecha" type="xs:date"/>

        <xs:element name="localidad" type="tipoLocalidad"
                    minOccurs="1" maxOccurs="unbounded"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="tipoLocalidad">
    <xs:sequence>
      <xs:element name="temperatura"   type="tipoTemperatura"/>
      <xs:element name="estado_cielo"  type="xs:string"/>
      <xs:element name="viento"        type="tipoViento"/>
      <xs:element name="estado_mar"    type="tipoEstadoMar"/>
    </xs:sequence>

    <xs:attribute name="nombre"    type="xs:string" use="required"/>
    <xs:attribute name="provincia" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:simpleType name="tipoTemperatura">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-50"/>
      <xs:maxInclusive value="60"/>
      <xs:fractionDigits value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoViento">

    <xs:simpleContent>
      <xs:extension base="xs:nonNegativeInteger">
        <xs:attribute name="direccion" type="tipoDireccion" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:simpleType name="tipoDireccion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Norte"/>
      <xs:enumeration value="Sur"/>
      <xs:enumeration value="Este"/>
      <xs:enumeration value="Oeste"/>
      <xs:enumeration value="Noreste"/>
      <xs:enumeration value="Noroeste"/>
      <xs:enumeration value="Sureste"/>
      <xs:enumeration value="Suroeste"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoEstadoMar">
    <xs:restriction base="xs:string">
      <xs:enumeration value="en calma"/>
      <xs:enumeration value="rizado"/>
      <xs:enumeration value="marejadilla"/>
      <xs:enumeration value="marejada"/>
      <xs:enumeration value="bravo"/>
      <xs:enumeration value="peligroso"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== aidansanchez07-prog/DAW/1-DAW/Lenguajes-de-Marcas/XML/Portal-meteorologico/clima.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clima.xsl"?>
<reporte_meteorologico
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="clima.xsd">

  <fecha>2026-05-20</fecha>

  <localidad nombre="Málaga" provincia="Andalucía">
    <temperatura>27.5</temperatura>
    <estado_cielo>Despejado</estado_cielo>
    <viento direccion="Sur">12</viento>
    <estado_mar>en calma</estado_mar>
  </localidad>

  <localidad nombre="Santander" provincia="Cantabria">
    <temperatura>16.2</temperatura>
    <estado_cielo>Lluvia débil</estado_cielo>
    <viento direccion="Noroeste">35</viento>
    <estado_mar>bravo</estado_mar>
  </localidad>

  <localidad nombre="Valencia" provincia="Comunidad Valenciana">
    <temperatura>25.0</temperatura>
    <estado_cielo>Intervalos nubosos</estado_cielo>
    <viento direccion="Este">18</viento>
    <estado_mar>peligroso</estado_mar>
  </localidad>

</reporte_meteorologico>
